// Données mock pour le développement et les tests
export const MOCK_GABON_COMPANIES = [
  {
    id: 'mock-1',
    name: 'Salon de Coiffure Élégance',
    bio: 'Salon de coiffure moderne à Libreville. Spécialités: tresses africaines, défrisage, coupe homme/femme. #SalonLibreville #BeautéGabon',
    profileImage: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=400',
    platform: 'facebook' as const,
    profileUrl: 'https://facebook.com/elegance-libreville',
    activityDomain: 'beauté',
    location: 'Libreville, Gabon',
    city: 'Libreville',
    followers: 1250,
    verified: false,
    gabonScore: 95,
    hashtags: ['#SalonLibreville', '#BeautéGabon', '#CoiffureAfricaine'],
    lastPostDate: new Date().toISOString(),
    phone: '+241 01 23 45 67',
    whatsapp: '+241 01 23 45 67',
    email: 'contact@elegance-ga.com'
  },
  {
    id: 'mock-2',
    name: 'Coiffure Prestige',
    bio: 'Votre salon de beauté à Port-Gentil. Services: coiffure afro, maquillage, manucure. Ouvert 7j/7.',
    profileImage: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400',
    platform: 'instagram' as const,
    profileUrl: 'https://instagram.com/prestige.portgentil',
    activityDomain: 'beauté',
    location: 'Port-Gentil, Gabon',
    city: 'Port-Gentil',
    followers: 3400,
    verified: true,
    gabonScore: 98,
    hashtags: ['#PortGentil', '#Beauté', '#SalonGabon'],
    lastPostDate: new Date().toISOString(),
    phone: '+241 07 98 76 54',
    website: 'https://prestige-pg.com'
  },
  {
    id: 'mock-3',
    name: 'Beauty Studio Franceville',
    bio: 'Institut de beauté complet à Franceville. Coiffure, esthétique, soins du visage.',
    profileImage: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?w=400',
    platform: 'facebook' as const,
    profileUrl: 'https://facebook.com/beautystudio.franceville',
    activityDomain: 'beauté',
    location: 'Franceville, Gabon',
    city: 'Franceville',
    followers: 890,
    verified: false,
    gabonScore: 92,
    hashtags: ['#Franceville', '#InstituBeauté', '#GabonBeauty'],
    lastPostDate: new Date().toISOString(),
    phone: '+241 06 45 32 18'
  },
  {
    id: 'mock-4',
    name: 'Restaurant Le Baobab',
    bio: 'Restaurant gastronomique gabonais à Libreville. Cuisine traditionnelle et moderne. Réservation: 01 76 54 32.',
    profileImage: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400',
    platform: 'facebook' as const,
    profileUrl: 'https://facebook.com/lebaobab.libreville',
    activityDomain: 'restauration',
    location: 'Libreville, Gabon',
    city: 'Libreville',
    followers: 5600,
    verified: true,
    gabonScore: 100,
    hashtags: ['#RestaurantGabon', '#CuisineGabonaise', '#Libreville'],
    lastPostDate: new Date().toISOString(),
    phone: '+241 01 76 54 32',
    website: 'https://lebaobab-ga.com',
    address: 'Boulevard Triomphal, Libreville'
  },
  {
    id: 'mock-5',
    name: 'Chez Maman',
    bio: 'Restaurant africain authentique. Spécialités: poulet nyembwé, poisson salé, manioc. Livraison disponible.',
    profileImage: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400',
    platform: 'instagram' as const,
    profileUrl: 'https://instagram.com/chezmaman.ga',
    activityDomain: 'restauration',
    location: 'Port-Gentil, Gabon',
    city: 'Port-Gentil',
    followers: 2100,
    verified: false,
    gabonScore: 97,
    hashtags: ['#CuisineAfricaine', '#PortGentil', '#FoodGabon'],
    lastPostDate: new Date().toISOString(),
    phone: '+241 07 23 45 67',
    whatsapp: '+241 07 23 45 67'
  },
  {
    id: 'mock-6',
    name: 'Boutique Mode Africaine',
    bio: 'Vêtements africains modernes et traditionnels. Wax, pagne, accessoires. Livraison Gabon.',
    profileImage: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=400',
    platform: 'instagram' as const,
    profileUrl: 'https://instagram.com/modeafricaine.ga',
    activityDomain: 'mode',
    location: 'Libreville, Gabon',
    city: 'Libreville',
    followers: 8900,
    verified: true,
    gabonScore: 96,
    hashtags: ['#ModeAfricaine', '#WaxGabon', '#FashionLibreville'],
    lastPostDate: new Date().toISOString(),
    phone: '+241 06 12 34 56',
    website: 'https://modeafricaine-ga.com',
    email: 'contact@modeafricaine-ga.com'
  },
  {
    id: 'mock-7',
    name: 'Hôtel Mont Bouët',
    bio: 'Hôtel 4 étoiles au cœur de Libreville. Chambres climatisées, restaurant, piscine, wifi gratuit.',
    profileImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400',
    platform: 'facebook' as const,
    profileUrl: 'https://facebook.com/hotelmontbouet',
    activityDomain: 'hôtellerie',
    location: 'Libreville, Gabon',
    city: 'Libreville',
    followers: 12000,
    verified: true,
    gabonScore: 99,
    hashtags: ['#HôtelLibreville', '#TourismeGabon', '#MontBouët'],
    lastPostDate: new Date().toISOString(),
    phone: '+241 01 44 55 66',
    website: 'https://hotelmontbouet.com',
    email: 'reservation@hotelmontbouet.com',
    address: 'Quartier Mont-Bouët, Libreville'
  },
  {
    id: 'mock-8',
    name: 'Pharmacie Centrale',
    bio: 'Pharmacie de garde 24h/24. Médicaments, parapharmacie, conseil santé. Livraison rapide Libreville.',
    profileImage: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=400',
    platform: 'facebook' as const,
    profileUrl: 'https://facebook.com/pharmaciecentrale.ga',
    activityDomain: 'santé',
    location: 'Libreville, Gabon',
    city: 'Libreville',
    followers: 4300,
    verified: true,
    gabonScore: 100,
    hashtags: ['#PharmacieGabon', '#SantéLibreville', '#Pharmacie24h'],
    lastPostDate: new Date().toISOString(),
    phone: '+241 01 77 88 99',
    whatsapp: '+241 01 77 88 99',
    email: 'contact@pharmaciecentrale.ga'
  },
  {
    id: 'mock-9',
    name: 'École Internationale du Gabon',
    bio: 'École privée bilingue (français/anglais). Maternelle à Terminale. Programme international.',
    profileImage: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=400',
    platform: 'facebook' as const,
    profileUrl: 'https://facebook.com/ecoleinternationale.ga',
    activityDomain: 'éducation',
    location: 'Libreville, Gabon',
    city: 'Libreville',
    followers: 6700,
    verified: true,
    gabonScore: 100,
    hashtags: ['#ÉducationGabon', '#ÉcoleLibreville', '#EnseignementInternational'],
    lastPostDate: new Date().toISOString(),
    phone: '+241 01 23 67 89',
    website: 'https://ecoleinternationale.ga',
    email: 'admission@ecoleinternationale.ga',
    address: 'Quartier Batterie IV, Libreville'
  },
  {
    id: 'mock-10',
    name: 'Garage Auto Expert',
    bio: 'Mécanique automobile toutes marques. Révision, réparation, pièces détachées. Devis gratuit.',
    profileImage: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=400',
    platform: 'facebook' as const,
    profileUrl: 'https://facebook.com/autoexpert.ga',
    activityDomain: 'automobile',
    location: 'Libreville, Gabon',
    city: 'Libreville',
    followers: 3100,
    verified: false,
    gabonScore: 94,
    hashtags: ['#GarageGabon', '#MécaniqueLibreville', '#AutoGabon'],
    lastPostDate: new Date().toISOString(),
    phone: '+241 06 98 76 54',
    whatsapp: '+241 06 98 76 54'
  }
];

// Fonction pour filtrer les données mock par requête
export function searchMockCompanies(query: string, limit: number = 10) {
  const queryLower = query.toLowerCase();
  
  return MOCK_GABON_COMPANIES.filter(company => {
    return (
      company.name.toLowerCase().includes(queryLower) ||
      company.bio.toLowerCase().includes(queryLower) ||
      company.activityDomain.toLowerCase().includes(queryLower) ||
      company.location.toLowerCase().includes(queryLower) ||
      company.hashtags.some(tag => tag.toLowerCase().includes(queryLower))
    );
  }).slice(0, limit);
}
